import {
    CheckIcon,
    HandThumbUpIcon,
    UserIcon,
} from "@heroicons/react/20/solid";
const timeline = [
    {
        id: 1,
        content: "Welcome to",
        target: "New User",
        href: "#",
        date: "Sep 20",
        datetime: "2020-09-20",
        icon: UserIcon,
        iconBackground: "bg-gray-400",
    },
    {
        id: 2,
        content: "Order Rated by",
        target: "Bethany Blake",
        href: "#",
        date: "Sep 22",
        datetime: "2020-09-22",
        icon: HandThumbUpIcon,
        iconBackground: "bg-blue-500",
    },
    {
        id: 3,
        content: "Verify",
        target: "New Seller",
        href: "#",
        date: "Sep 20",
        datetime: "2020-09-20",
        icon: UserIcon,
        iconBackground: "bg-gray-400",
    },
    {
        id: 4,
        content: "Order Delivered",
        target: "Martha Gardner",
        href: "#",
        date: "Sep 28",
        datetime: "2020-09-28",
        icon: CheckIcon,
        iconBackground: "bg-green-500",
    },
    {
        id: 5,
        content: "Order Rated by",
        target: "Bethany Blake",
        href: "#",
        date: "Sep 30",
        datetime: "2020-09-30",
        icon: HandThumbUpIcon,
        iconBackground: "bg-blue-500",
    },
    {
        id: 6,
        content: "Order successfully Delivered",
        target: "Katherine Snyder",
        href: "#",
        date: "Oct 4",
        datetime: "2020-10-04",
        icon: CheckIcon,
        iconBackground: "bg-green-500",
    },
];
export { timeline };
